services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    build: .
    volumes:
      - ./html:/var/www/html

  php-cli:
    image: php:8.2-cli
    volumes:
      - ./html:/var/www/html
    working_dir: /var/www/html
